variables:
  - name: ReleaseEnvironmentName
    value: DEV
  - name: WebAppPrefix
    value: dfc-dev-app-lmi-delta-report
  - name: EnableAzureMonitorAlerting
    value: true
  - name: ResourceGroup
    value: $(WebAppPrefix)-rg
  - name: aspTier
    value: Standard
  - name: aspInstances
    value: 2
  - name: aspSize
    value: 2
  - name: DeltaReportApiClientOptionsBaseAddress
    value: https://dfc-dev-draft-api-lmi-delta-report-fa.$(appServiceDomain)/delta-reports/