variables:
  - name: ReleaseEnvironmentName
    value: PP
  - name: resourcePrefix
    value: dfc-pp-app-lmi-delta-report
  - name: appServiceName
    value: $(resourcePrefix)-as-ver2
  - name: appServicePlanSuffix
    value: -migrated
  - name: ResourceGroup
    value: $(resourcePrefix)-rg
  - name: EnableAzureMonitorAlerting
    value: true
  - name: DeltaReportApiClientOptionsBaseAddress
    value: https://dfc-pp-api-lmi-delta-report-fa-ver2.$(appServiceDomain)/delta-reports/