variables:
  - name: ReleaseEnvironmentName
    value: SIT
  - name: WebAppPrefix
    value: dfc-sit-app-lmi-delta-report
  - name: ResourceGroup
    value: $(WebAppPrefix)-rg
  - name: aspTier
    value: Standard
  - name: aspInstances
    value: 2
  - name: aspSize
    value: 2
  - name: DeltaReportApiClientOptionsBaseAddress
    value: https://dfc-sit-draft-api-lmi-delta-report-fa.$(appServiceDomain)/delta-reports/